<?php // DO NOT out any HTML above this line
//index.php
require_once "pdo.php"; // DB connection
require_once "util.php"; // common utils

// continue the session
session_start();

// End Script / Die if username is NOT set
if ( ! isset($_SESSION['name']) || strlen($_SESSION['name']) < 1  ) {
    die("ACCESS DENIED");
}

// If the user cancelled Add request, redirect back to index.php
if ( isset($_POST['cancel']) ) {
    header('Location: index.php');
    return;
}

// MODEL : POST Handling - Add Profile & Positions to the DB based on
// user inputs retrieved from the POST response
if ( isset($_POST['first_name']) && isset($_POST['last_name']) &&
     isset($_POST['email']) && isset($_POST['headline']) &&
     isset($_POST['summary'])) {

    // Profile Form Validations
    $msg = validateProfile();
    if ( is_string($msg) ){
      $_SESSION['error'] = $msg;
      header("Location: add.php");
      return;
      }

    // Validate Position entries if present
    $msg = validatePos();
    if ( is_string($msg) ){
      $_SESSION['error'] = $msg;
      header("Location: add.php");
      return;
      }

    // Insert Profile record in DB
    $sql = "INSERT INTO Profile (user_id, first_name, last_name, email, headline, summary)
              VALUES (:uid, :fn, :ln, :em, :he, :su)";

    $stmt = $pdo->prepare($sql);
    $stmt->execute(array(
        ':uid' => $_SESSION['user_id'],
        ':fn' => $_POST['first_name'],
        ':ln' => $_POST['last_name'],
        ':em' => $_POST['email'],
        ':he' => $_POST['headline'],
        ':su' => $_POST['summary']));

    // get the profile-id generated by INSERT operation above, to be used as FK for Position table
    $profile_id = $pdo->lastInsertId();

    // Insert the position entries in DB
    $rank = 1;
    for ($i = 1; $i <=9; $i++){
      if ( ! is_string($_POST['year'.$i] ) ) continue;
      if ( ! is_string($_POST['desc'.$i] ) ) continue;
      $year = $_POST['year'.$i];
      $desc = $_POST['desc'.$i];

      $stmt = $pdo->prepare('INSERT INTO position
              (profile_id, rank, year, description)
              VALUES (:pid, :rank, :year, :desc)');

      $stmt->execute(array(
          ':pid' => $profile_id,
          ':rank' => $rank,
          ':year' => $year,
          ':desc' => $desc)
        );
      $rank ++;
    }

    $_SESSION['success'] = "Profile added";
    header("Location: index.php");
    return;
    }
?>

<!DOCTYPE html>
<html>
<head>
<title>Hasan Mujtaba - CRUD/JS Resume Registry</title>
<?php require_once "bootstrap.php"; ?>
</head>

<body>
<div class="container">
<h1>Adding Profile for <?= htmlentities($_SESSION['name']); ?></h1>

<?php
// Flash error message if form validations fail, 1x only
flashMessages();
?>

<form method="post">
<p>First Name: <input type="text" name="first_name" size="60"/></p>
<p>Last Name: <input type="text" name="last_name" size="60"/></p>
<p>Email: <input type="text" name="email"/></p>
<p>Headline:<br/> <input type="text" name="headline"/></p>
<p>Summary:<br/><textarea name="summary", rows="8", cols="80" /></textarea></p>
<p>Position:<input type="submit" id="addPos" value="+">
<div id="position_fields">
</div>
</p>
<p><input type="submit" name="add" value="Add">
<input type="submit" name="cancel" value="Cancel"></p>
</form>

<script>
countPos = 0;
// http://stackoverflow.com/questions/17650776/add-remove-html-inside-div-using-javascript
$(document).ready(function(){
    window.console && console.log('Document ready called');
    $('#addPos').click(function(event){
        // http://api.jquery.com/event.preventdefault/
        event.preventDefault();
        if ( countPos >= 9 ) {
            alert("Maximum of nine position entries exceeded");
            return;
        }
        countPos++;
        window.console && console.log("Adding position "+countPos);
        $('#position_fields').append(
            '<div id="position'+countPos+'"> \
            <p>Year: <input type="text" name="year'+countPos+'" value="" /> \
            <input type="button" value="-" \
            onclick="$(\'#position'+countPos+'\').remove();return false;"></p> \
            <textarea name="desc'+countPos+'" rows="8" cols="80"></textarea>\
            </div>');
    });
});
</script>

</div>
</body>
</html>
